# -*- coding: utf-8 -*-
"""

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10tHPnJ6-bmM959JRVSUugXRxVJC_84YN

# Imports
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold

from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds);

"""# Data"""

sheet = gc.open('ACME-HappinessSurvey2020').sheet1;

all_data = sheet.get_all_values();

headers = all_data[0];
records = all_data[1:];
data = pd.DataFrame.from_records(records, columns=headers);

#de-stringify
for col in data.columns:
    data[col] = pd.to_numeric(data[col]);

yTrain = np.array(data['Y'])
xTrains = np.array(data.iloc[:,1:])

"""#Correlation"""

#data_noY = data.iloc[1:,1:]
correls = data.corr().round(2)
#print(correls)

import seaborn as sb
heatmap = sb.heatmap(correls,annot=True)

#from pandas.plotting import scatter_matrix
#features = ["total_rooms", "population", "households", "median_house_value"]
#scatter_matrix(data_noY, figsize=(12, 8))

"""# Grid Search

https://machinelearningmastery.com/hyperparameters-for-classification-machine-learning-algorithms/

Logistic Regression
"""

# define models and parameters
model = LogisticRegression()

solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]

# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains,yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

"""SVM"""

# define model and parameters
model = svm.SVC()

kernel = ['poly', 'rbf', 'sigmoid']
C = [50, 10, 1.0, 0.1, 0.01]
gamma = ['scale']

# define grid search
grid = dict(kernel=kernel,C=C,gamma=gamma)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains,yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

"""Decision Tree (Bagging)"""

# define models and parameters
model = BaggingClassifier()

n_estimators = [10, 100, 1000]

# define grid search
grid = dict(n_estimators=n_estimators)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains, yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

"""Decision Tree"""

# define models and parameters
model = DecisionTreeClassifier()

max_depth = np.arange(1,10)
max_features = [None, 'sqrt', 'log2']

path = model.cost_complexity_pruning_path(xTrains,yTrain)
ccp_alphas = path.ccp_alphas

# define grid search
grid = dict(max_depth=max_depth,max_features=max_features,ccp_alpha=ccp_alphas)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains, yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

"""Random Forest"""

# define models and parameters
model = RandomForestClassifier()

n_estimators = [10, 100, 1000]
max_features = ['sqrt', 'log2']

# define grid search
grid = dict(n_estimators=n_estimators,max_features=max_features)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains, yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

"""Naive Bayes"""

# define models and parameters
model = GaussianNB()

var_smoothing = np.logspace(0,-9, num=10)

# define grid search
grid = dict(var_smoothing = var_smoothing)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains, yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

"""KNN"""

# define models and parameters
model = KNeighborsClassifier()

n_neighbors = range(1, 21, 2)
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']

# define grid search
grid = dict(n_neighbors=n_neighbors,weights=weights,metric=metric)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

grid_search = GridSearchCV(estimator=model, param_grid=grid, cv=cv, scoring='f1')
grid_result = grid_search.fit(xTrains, yTrain)

# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
